 <outputConfig>
  <type>csv</type>
  <requiredData>
   <id>"scm":3:12:0</id>
   <id>"scm":3:12:1</id>
   <id>"scm":3:12:2</id>
   <id>"scm":3:12:8</id>
   <id>"scm":3:4:"name"</id>
   <id>"scm":3:4:"message"</id>
   <id>"scm":3:4:"state"</id>
   <id>"scm":3:3:"name"</id>
   <id>"scm":3:3:"message"</id>
  </requiredData>
  <csvConfig>
   <timeFormat>absolute</timeFormat>
   <enumFormat>numeric</enumFormat>
   <signSuffix>disable</signSuffix>
   <columnHeaders>enable</columnHeaders>
   <filename>OUTPUTDIR/vehicle_processor.csv</filename>
  </csvConfig>
 </outputConfig>
